[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.xml
  | \.iml
  | \.json
  | \.txt
  | \.md
  | \.mypy_cache
  | \.ts
  | \.js
  | \.html
  | \.css
  | \.scss
  | \.tsx
  | \.jenkins
  | \.yaml


)/
'''