# Generated by Django 3.0.7 on 2020-10-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQAMetricsFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "filtration_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("drop-down", "Drop-down"),
                            ("numeric", "Numeric"),
                            ("date", "Date"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.UserSettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPredictionsTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_default", models.BooleanField(default=False)),
                ("position", models.IntegerField()),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.UserSettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "filtration_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("drop-down", "Drop-down"),
                            ("numeric", "Numeric"),
                            ("date", "Date"),
                        ],
                        default="string",
                        max_length=128,
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.UserSettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.Team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamQAMetricsFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "filtration_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("drop-down", "Drop-down"),
                            ("numeric", "Numeric"),
                            ("date", "Date"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.TeamSettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamPredictionsTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("is_default", models.BooleanField(default=False)),
                ("position", models.IntegerField()),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.TeamSettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "filtration_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("drop-down", "Drop-down"),
                            ("numeric", "Numeric"),
                            ("date", "Date"),
                        ],
                        default="string",
                        max_length=128,
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.TeamSettings",
                    ),
                ),
            ],
        ),
    ]
