# Generated by Django 3.0.7 on 2020-12-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('string', 'String'), ('drop-down', 'Drop-down'), ('numeric', 'Numeric'), ('date', 'Date')], default='string', max_length=128)),
            ],
            options={
                'db_table': 'user_filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPredictionsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
            ],
            options={
                'db_table': 'user_predictions_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserQAMetricsFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('string', 'String'), ('drop-down', 'Drop-down'), ('numeric', 'Numeric'), ('date', 'Date')], max_length=128)),
            ],
            options={
                'db_table': 'user_qa_metrics_filter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTrainingParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('training_parameters', models.TextField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UserSettings')),
            ],
            options={
                'db_table': 'user_training_parameters',
            },
        ),
        migrations.CreateModel(
            name='UserTopTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_terms_object', models.BinaryField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UserSettings')),
            ],
            options={
                'db_table': 'user_top_terms',
            },
        ),
        migrations.CreateModel(
            name='UserSourceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UserSettings')),
            ],
            options={
                'db_table': 'user_source_field',
            },
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('model', models.BinaryField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UserSettings')),
            ],
            options={
                'db_table': 'user_models',
            },
        ),
        migrations.CreateModel(
            name='UserMarkUpEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('entities', models.TextField()),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UserSettings')),
            ],
            options={
                'db_table': 'user_mark_up_entity',
            },
        ),
        migrations.CreateModel(
            name='UserBugResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UserSettings')),
            ],
            options={
                'db_table': 'user_bug_resolution',
            },
        ),
    ]
